# Prometheus Configuration for ERIP Platform
# Comprehensive monitoring and alerting setup

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # ERIP Backend Application
  - job_name: 'erip-backend'
    static_configs:
      - targets: ['erip-backend:8001']
    scrape_interval: 15s
    metrics_path: /metrics
    honor_labels: true
    scrape_timeout: 10s

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # AWS CloudWatch Exporter
  - job_name: 'cloudwatch-exporter'
    static_configs:
      - targets: ['cloudwatch-exporter:9106']
    scrape_interval: 60s

  # Application Load Balancer
  - job_name: 'aws-alb'
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        filters:
          - name: tag:Name
            values: 
              - erip-alb-*
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance

  # ECS Tasks Discovery
  - job_name: 'ecs-tasks'
    ecs_sd_configs:
      - region: us-east-1
        cluster: erip-cluster-production
        task_definitions:
          - erip-backend-production
    relabel_configs:
      - source_labels: [__meta_ecs_task_definition_family]
        target_label: job
      - source_labels: [__meta_ecs_container_name]
        target_label: container
      - source_labels: [__address__]
        regex: '([^:]+):.*'
        target_label: instance
        replacement: '€{1}:8001'

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Remote write to AWS Managed Prometheus (if using)
# remote_write:
#   - url: https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-xxx/api/v1/remote_write
#     sigv4:
#       region: us-east-1